# --- Gateway Connection ---
gateways:
  postgres:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connection
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/postgres/#connection-options
      type: postgres
      host: ep-summer-block-ajitaxb1.c-3.us-east-2.aws.neon.tech 
      user: neondb_owner 
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      database: neondb 
      # concurrent_tasks: 4
      # register_comments: True
      # pre_ping: True
      # pretty_sql: False
      # schema_differ_overrides: 
      # catalog_type_overrides: 
      # keepalives_idle: 
      # connect_timeout: 10
      # role: 
      sslmode: require
      # application_name: 

default_gateway: postgres

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: postgres
  start: 2026-06-18 # Start date for backfill history
  cron: '@weekly'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections
